###
POST http://localhost:5000/book-seat 
Content-Type: application/json

{     "id": 3,
      "availabillity": "booked",
      "seat": 5,
      "category": "Premium"
}
###

GET http://localhost:5000/booked
###
GET http://localhost:5000/available-seats